# Use an official lightweight Node.js image as the base image
FROM node:alpine

# Set the working directory inside the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . .

# Install dependencies (if any)
RUN npm install

# Expose the port the app will run on
EXPOSE 80

# Command to run the application
CMD ["node", "server.js"]
